name: Tasks Python Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Configura o ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Define o paht PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run tests
      run: python -m unittest discover -s . -p 'test_*.py'
